# _quarto.yml

project:
  type: website
  output-dir: docs
  resources:
    - "Assignments/_templates"


website:
  title: "NPHD 9040"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Syllabus"
        href: Other/syl.qmd
      - text: "Lectures"
        menu:
          - text: "Getting Started with R"
            href: Lectures/getting-started-with-r.qmd
          - text: "Preliminaries"
            href: Lectures/preliminaries.qmd
          - text: "Graphing Your Data"
            href: Lectures/graphing-your-data.qmd
          - text: "Introduction to ANOVA"
            href: Lectures/introduction-to-anova.qmd
          - text: "Introduction to ANCOVA"
            href: Lectures/introduction-to-ancova.qmd
          - text: "Introduction to Two-Way ANOVA"
            href: Lectures/introduction-to-two-way-anova.qmd
          - text: "Introduction to Repeated Measures ANOVA"
            href: Lectures/introduction-to-repeated-measures-anova.qmd
          - text: "Introduction to Simple Linear Regression"
            href: Lectures/introduction-to-simple-linear-regression.qmd
          - text: "Introduction to Multiple Linear Regression"
            href: Lectures/introduction-to-multiple-linear-regression.qmd
          - text: "Introduction to Logistic Regression"
            href: Lectures/introduction-to-logistic-regression.qmd
          - text: "Q&A for EBP and QI Projects"
            href: Lectures/QI_and_EBP.qmd
      - text: "Flashcards"
        menu:
          - text: "ANOVA"
            href: Flashcards/flashcards_anova.qmd
          - text: "2-Way ANOVA"
            href: Flashcards/flashcards_2wanova.qmd
      - text: "Assignments"
        menu:
          - text: "HW1"
            href: Assignments/hw1.qmd
          - text: "HW2"
            href: Assignments/hw2.qmd
          - text: "HW3"
            href: Assignments/hw3.qmd
          - text: "HW4"
            href: Assignments/hw4.qmd
          - text: "HW5"
            href: Assignments/hw5.qmd

          - text: "Midterm Presentation"
            href: Assignments/midterm.qmd
          - text: "Final Project"
            href: Assignments/final.qmd
      - text: "About Dr. L"
        href: Other/aboutDrL.qmd

format:
  html:
    toc: true
    toc-depth: 3
    theme: journal
    columns: 12
    css: styles.css




